// START OF UPDATED data.js

// data.js
// Contains the PRODUCTS and ALTERNATIVE RECOMMENDATIONS data.

export const PRODUCTS = [
    // --- Existing Products --- (IDs 1-14 remain the same as in your original file)
    {
        id: "1", barcode: "9780201379624", name: "Dark Chocolate Bar", description: "70% cocoa dark chocolate bar with hints of vanilla.", healthScore: 65, category: "Chocolate", image: "https://images.unsplash.com/photo-1511381939415-e340152efb59?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGFyayUyMGNob2NvbGF0ZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", brand: "Choco Delights", lastUpdated: "Today", calories: 180, servingSize: "per 30g (3 squares)", nutrients: { carbs: 13, protein: 2, fat: 12 }, ingredients: ["Cocoa Mass", "Cocoa Butter", "Sugar", "Vanilla Extract", "Soy Lecithin"], allergens: "May contain traces of milk, nuts, and wheat", healthStatus: "moderate",
        price: 150, pricePerServing: 50, valueRating: 7, incomeSuitability: ["medium_low", "medium_high", "high"]
    },
    {
        id: "2", barcode: "5012345678900", name: "Milk Chocolate Biscuits", description: "Crispy biscuits coated with milk chocolate.", healthScore: 35, category: "Biscuits", image: "https://images.unsplash.com/photo-1604151808439-8649cc74441a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2hvY29sYXRlJTIwYmlzY3VpdHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", brand: "Sweet Treats", lastUpdated: "Yesterday", calories: 240, servingSize: "per 50g (5 biscuits)", nutrients: { carbs: 28, protein: 3, fat: 14 }, ingredients: ["Wheat Flour", "Sugar", "Vegetable Oil", "Milk Chocolate (30%)", "Salt", "Raising Agents"], allergens: "Contains wheat, milk, and soy. May contain traces of nuts.", healthStatus: "unhealthy",
        price: 80, pricePerServing: 16, valueRating: 5, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },
    {
        id: "3", barcode: "8901234567890", name: "Organic Fruit & Nut Bar", description: "Natural energy bar made with organic dried fruits and nuts.", healthScore: 85, category: "Snack Bars", image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZnJ1aXQlMjBudXQlMjBiYXJ8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", brand: "Nature's Best", lastUpdated: "2 days ago", calories: 150, servingSize: "per 35g bar", nutrients: { carbs: 22, protein: 5, fat: 7 }, ingredients: ["Dates", "Almonds", "Cashews", "Raisins", "Sunflower Seeds"], allergens: "Contains tree nuts. Manufactured in a facility that processes peanuts.", healthStatus: "healthy",
        price: 180, pricePerServing: 180, valueRating: 8, incomeSuitability: ["medium_high", "high"]
    },
    {
        id: "4", barcode: "6809011904814", name: "Potato Chips Original", description: "Classic salted potato chips.", healthScore: 25, category: "Chips", image: "https://images.unsplash.com/photo-1599490659213-4cee7ff52b59?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG90YXRvJTIwY2hpcHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", brand: "Crispy Crunch", lastUpdated: "3 days ago", calories: 220, servingSize: "per 40g (1 handful)", nutrients: { carbs: 22, protein: 2, fat: 15 }, ingredients: ["Potatoes", "Vegetable Oil", "Salt"], allergens: "May contain traces of wheat.", healthStatus: "unhealthy",
        price: 30, pricePerServing: 30, valueRating: 4, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },
    {
        id: "5", barcode: "8904117900739", name: "Organic Quinoa", description: "High-protein, gluten-free organic quinoa grains. Versatile and nutritious base for meals.", healthScore: 90, category: "Grains", image: "https://organicindia.com/cdn/shop/products/Quinoa_ing.jpg?v=1672736693", brand: "HealthyGrains", lastUpdated: "Recently Added", calories: 184, servingSize: "per 50g serving", nutrients: { carbs: 32.1, protein: 7.1, fat: 3.1 }, ingredients: ["Organic Quinoa"], allergens: "None known. Processed in a facility that may handle nuts.", healthStatus: "healthy",
        price: 350, pricePerServing: 35, valueRating: 7, incomeSuitability: ["medium_low", "medium_high", "high"]
    },
    {
        id: "6", barcode: "6164000276125", name: "Brown Rice", description: "Whole grain brown rice, a good source of fiber and complex carbohydrates.", healthScore: 84, category: "Grains", image: "https://images.unsplash.com/photo-1595514524374-a4410aabcb03?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YnJvd24lMjByaWNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", brand: "NatureChoice", lastUpdated: "Recently Added", calories: 180, servingSize: "per 50g dry serving", nutrients: { carbs: 38.1, protein: 4.0, fat: 1.4 }, ingredients: ["Brown Rice"], allergens: "None known.", healthStatus: "healthy",
        price: 120, pricePerServing: 6, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },
    {
        id: "7", barcode: "5000108022152", name: "Oats (Rolled)", description: "Heart-healthy rolled oats, excellent source of soluble fiber.", healthScore: 94, category: "Oats", image: "https://images.unsplash.com/photo-1587613864870-9545c8f0f6c7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cm9sbGVkJTIwb2F0c3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", brand: "HeartHarvest", lastUpdated: "Recently Added", calories: 153, servingSize: "per 40g serving", nutrients: { carbs: 26.5, protein: 5.4, fat: 2.8 }, ingredients: ["Rolled Oats"], allergens: "May contain traces of wheat (processed in same facility).", healthStatus: "healthy",
        price: 150, pricePerServing: 6, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },
    {
        id: "8", barcode: "8906055441657", name: "Buckwheat Flour", description: "Nutritious gluten-free flour made from buckwheat groats (Kuttu ka Atta).", healthScore: 86, category: "Flour", image: "https://images.unsplash.com/photo-1597040790454-916214ea94a9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YnVja3doZWF0JTIwZmxvdXJ8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", brand: "EarthyEats", lastUpdated: "Recently Added", calories: 185, servingSize: "per 50g serving", nutrients: { carbs: 35.8, protein: 6.7, fat: 1.7 }, ingredients: ["Buckwheat Flour"], allergens: "None known.", healthStatus: "healthy",
        price: 180, pricePerServing: 18, valueRating: 8, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },
    {
        id: "9", barcode: "4556977991262", name: "Chia Seeds", description: "Tiny seeds packed with omega-3 fatty acids, fiber, and protein.", healthScore: 96, category: "Seeds", image: "https://images.unsplash.com/photo-1541713361671-96c6d5b5f4d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpYSUyMHNlZWRzfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", brand: "NutriSeed", lastUpdated: "Recently Added", calories: 153, servingSize: "per 30g serving", nutrients: { carbs: 12.6, protein: 5.0, fat: 9.2 }, ingredients: ["Chia Seeds"], allergens: "None known.", healthStatus: "healthy",
        price: 250, pricePerServing: 30, valueRating: 7, incomeSuitability: ["medium_low", "medium_high", "high"]
    },
    {
        id: "10", barcode: "8901725000899", name: "Millet Mix", description: "A blend of various nutritious millet grains (like Ragi, Bajra, Jowar), naturally gluten-free.", healthScore: 82, category: "Grains", image: "https://images.unsplash.com/photo-1621588433159-42a6d700c6d2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWlsbGV0fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", brand: "GrainBlend", lastUpdated: "Recently Added", calories: 176, servingSize: "per 50g dry serving", nutrients: { carbs: 33.5, protein: 5.5, fat: 2.3 }, ingredients: ["Mixed Millets (e.g., Foxtail, Finger, Pearl)"], allergens: "None known.", healthStatus: "healthy",
        price: 160, pricePerServing: 8, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },
    {
        id: "11", barcode: "6164000025303", name: "Lentils (Red Masoor)", description: "Quick-cooking red lentils (Masoor Dal), high in protein and fiber.", healthScore: 92, category: "Pulses", image: "https://images.unsplash.com/photo-1613430096641-a1f7f16e8d90?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmVkJTIwbGVudGlsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", brand: "PulsePerfect", lastUpdated: "Recently Added", calories: 176, servingSize: "per 50g dry serving", nutrients: { carbs: 30.1, protein: 12.9, fat: 0.5 }, ingredients: ["Red Lentils (Masoor Dal)"], allergens: "None known.", healthStatus: "healthy",
        price: 90, pricePerServing: 5, valueRating: 10, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },
    {
        id: "12", barcode: "8902901232806", name: "Flax Seeds", description: "Rich source of omega-3 fatty acids (ALA), lignans, and fiber (Alsi).", healthScore: 88, category: "Seeds", image: "https://images.unsplash.com/photo-1591189863413-11998a4ccff9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZmxheCUyMHNlZWRzfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", brand: "OmegaPower", lastUpdated: "Recently Added", calories: 171, servingSize: "per 30g serving", nutrients: { carbs: 8.7, protein: 5.5, fat: 12.7 }, ingredients: ["Flax Seeds"], allergens: "None known.", healthStatus: "healthy",
        price: 200, pricePerServing: 24, valueRating: 7, incomeSuitability: ["medium_low", "medium_high", "high"]
    },
    {
        id: "13", barcode: "841079009896", name: "Whole Wheat Pasta", description: "Pasta made from whole wheat flour, providing more fiber than regular pasta.", healthScore: 78, category: "Pasta", image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2hvbGUlMjB3aGVhdCUyMHBhc3RhfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", brand: "FitFuel", lastUpdated: "Recently Added", calories: 300, servingSize: "per 80g dry serving", nutrients: { carbs: 60.0, protein: 10.4, fat: 2.0 }, ingredients: ["Whole Wheat Durum Semolina"], allergens: "Contains Wheat.", healthStatus: "healthy",
        price: 130, pricePerServing: 21, valueRating: 7, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },
    {
        id: "14", barcode: "8906156483495", name: "Sprouted Moong", description: "Sprouted moong beans (green gram), highly digestible and rich in nutrients.", healthScore: 98, category: "Pulses", image: "https://images.unsplash.com/photo-1600778225398-651988d13498?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3Byb3V0ZWQlMjBtb29uZyUyMGJlYW5zfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", brand: "GreenPulse", lastUpdated: "Recently Added", calories: 165, servingSize: "per 50g serving", nutrients: { carbs: 28.0, protein: 12.0, fat: 0.6 }, ingredients: ["Sprouted Moong Beans"], allergens: "None known.", healthStatus: "healthy",
        price: 100, pricePerServing: 20, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },

    {
        id: "15", barcode: "8901491361026", name: "Kurkure Masala Munch", description: "Spicy, crunchy corn-based snack.", healthScore: 20, category: "Chips/Snacks", image: "https://www.bigbasket.com/media/uploads/p/xxl/102761_18-kurkure-namkeen-masala-munch.jpg", brand: "Kurkure", lastUpdated: "Recently Added", calories: 214, servingSize: "per 40g pack", nutrients: { carbs: 22, protein: 3, fat: 13 }, ingredients: ["Rice Meal", "Edible Vegetable Oil", "Corn Meal", "Gram Meal", "Spices & Condiments", "Salt", "Sugar", "Citric Acid", "Tartaric Acid"], allergens: "May contain traces of wheat, soy.", healthStatus: "unhealthy",
        price: 20, pricePerServing: 20, valueRating: 6, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },
    {
        id: "16", barcode: "6001065225906", name: "Dairy Milk Chocolate", description: "Classic milk chocolate bar.", healthScore: 30, category: "Chocolate", image: "https://neelamfoodlandmumbai.com/cdn/shop/files/3301_1_1024x1024.jpg?v=1736099335", brand: "Cadbury", lastUpdated: "Recently Added", calories: 209, servingSize: "per 40g bar", nutrients: { carbs: 22, protein: 3, fat: 12 }, ingredients: ["Milk Solids", "Sugar", "Cocoa Butter", "Cocoa Mass", "Emulsifiers (442, 476)", "Flavours (Natural, Nature Identical and Artificial (Vanilla))"], allergens: "Contains Milk. Manufactured on equipment that also processes products containing tree nuts and wheat.", healthStatus: "unhealthy",
        price: 45, pricePerServing: 45, valueRating: 5, incomeSuitability: ["low", "medium_low", "medium_high", "high"]
    },
];

export const ALTERNATIVES = {
    // --- Existing Alternatives (IDs 1-14 remain the same as in your original file) ---
    "1": [
        { id: "alt1-1", name: "Banana + Peanut Butter", description: "Naturally sweet banana with protein-rich peanut butter. A satisfying, healthier treat.", healthScore: 85, image: "https://images.unsplash.com/photo-1615478503562-ec2d8aa0e24e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmFuYW5hJTIwcGVhbnV0JTIwYnV0dGVyfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 40, pricePerServing: 40, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt1-2", name: "Greek Yogurt + Cocoa + Berries", description: "High-protein yogurt with unsweetened cocoa and antioxidant-rich berries.", healthScore: 90, image: "https://images.unsplash.com/photo-1587477615013-357d68b6951a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JlZWslMjB5b2d1cnQlMjBjaG9jb2xhdGUlMjBiZXJyaWVzfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 80, pricePerServing: 80, valueRating: 8, incomeSuitability: ["medium_low", "medium_high", "high"] },
        { id: "alt1-3", name: "Amul 90% Dark Chocolate", description: "Very dark chocolate with lower sugar content. Intense cocoa flavour.", healthScore: 75, image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRYzOJvAhNUgdflE1jxmPPQFxi6Ja72lxvPDY1qRudbag66Rp8IJQrZSZ0I9R_M4Vczs6xEM1uEY4G31Jbb3ZIhl5nlD9unjbCs6KZdR_3kfc6MaYqLzHNQUA", healthStatus: "moderate", price: 130, pricePerServing: 43, valueRating: 8, incomeSuitability: ["medium_low", "medium_high", "high"] }
    ],
    "2": [
        { id: "alt2-1", name: "Whole Wheat Digestive Biscuits", description: "Biscuits made with whole wheat flour, higher in fiber.", healthScore: 60, image: "https://images.unsplash.com/photo-1625899024968-f1a1f06f84d4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZGlnZXN0aXZlJTIwYmlzY3VpdHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "moderate", price: 50, pricePerServing: 10, valueRating: 7, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt2-2", name: "Oat Cookies (e.g., Britannia NutriChoice)", description: "Cookies with oats as a primary ingredient, often with less refined sugar.", healthScore: 65, image: "https://www.jiomart.com/images/product/original/491601014/britannia-nutrichoice-digestive-oats-biscuits-100-g-product-images-o491601014-p491601014-0-202203150149.jpg", healthStatus: "moderate", price: 60, pricePerServing: 12, valueRating: 7, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt2-3", name: "Ragi Crackers + Fruit Spread", description: "Crunchy millet crackers with natural fruit jam (low sugar).", healthScore: 75, image: "https://plus.unsplash.com/premium_photo-1676089963418-8cabc3768666?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y3JhY2tlcnMlMjBqYW18ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 70, pricePerServing: 70, valueRating: 8, incomeSuitability: ["medium_low", "medium_high", "high"] }
    ],
    "3": [
        { id: "alt3-1", name: "Homemade Trail Mix (Nuts, Seeds, Raisins)", description: "Control ingredients and sugar by mixing your own nuts, seeds (like pumpkin/sunflower), and dried fruit.", healthScore: 90, image: "https://images.unsplash.com/photo-1499701850197-f690a4155850?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG9tZW1hZGUlMjB0cmFpbCUyMG1peHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 150, pricePerServing: 30, valueRating: 9, incomeSuitability: ["medium_low", "medium_high", "high"] },
        { id: "alt3-2", name: "Apple Slices + Peanut Butter", description: "Simple, whole food snack providing fiber, vitamins, and healthy fats.", healthScore: 88, image: "https://images.unsplash.com/photo-1608198093002-442a72909a55?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YXBwbGUlMjBwZWFudXQlMjBidXR0ZXJ8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 45, pricePerServing: 45, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt3-3", name: "Roasted Chana (Chickpeas)", description: "Crunchy, savory, and protein-packed roasted chickpeas. Widely available.", healthScore: 82, image: "https://images.unsplash.com/photo-1604467707600-5c7adbce6c63?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cm9hc3RlZCUyMGNoaWNrcGVhc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 80, pricePerServing: 14, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt3-4", name: "Peanut Chikki / Gud Patti", description: "Traditional Indian sweet made with peanuts and jaggery. Provides energy, better than refined sugar bars.", healthScore: 70, image: "https://images.unsplash.com/photo-1603739457775-557a11b79616?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGVhbnV0JTIwY2hpa2tpc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "moderate", price: 50, pricePerServing: 18, valueRating: 8, incomeSuitability: ["low", "medium_low", "medium_high", "high"] }
    ],
    "4": [
        { id: "alt4-1", name: "Baked Ragi Chips / Nachos", description: "Crunchy baked snacks made from Ragi (finger millet) flour. Healthier than fried potato chips.", healthScore: 70, image: "https://m.media-amazon.com/images/I/81a4ZtUeWSL.jpg", healthStatus: "moderate", price: 60, pricePerServing: 40, valueRating: 7, incomeSuitability: ["medium_low", "medium_high", "high"] },
        { id: "alt4-2", name: "Air-popped Popcorn (Lightly Salted)", description: "Whole grain, high-fiber snack when air-popped and lightly seasoned.", healthScore: 85, image: "https://images.unsplash.com/photo-1578849248041-36f7a84beb70?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cG9wY29ybnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 50, pricePerServing: 5, valueRating: 10, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt4-3", name: "Spiced Puffed Rice (Murmura Bhel - No Sev)", description: "Light puffed rice mixed with onions, tomatoes, and spices (skip fried sev for health).", healthScore: 75, image: "https://images.unsplash.com/photo-1601050690594-787f8d7c07f8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bXVybXVyYSUyMGJoZWx8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 70, pricePerServing: 15, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt4-4", name: "Roasted Chana (Chickpeas)", description: "Crunchy, savory, and protein-packed roasted chickpeas.", healthScore: 82, image: "https://images.unsplash.com/photo-1604467707600-5c7adbce6c63?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cm9hc3RlZCUyMGNoaWNrcGVhc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 80, pricePerServing: 16, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
    ],
    "5": [
        { id: "alt5-1", name: "Millets (Ragi, Bajra, Jowar, Foxtail)", description: "Nutrient-dense Indian staple grains, naturally gluten-free, cheaper than quinoa.", healthScore: 85, image: "https://images.unsplash.com/photo-1621588433159-42a6d700c6d2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWlsbGV0fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 160, pricePerServing: 8, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt5-2", name: "Dalia (Broken Wheat)", description: "Cracked wheat, good source of fiber and commonly used for porridge or upma.", healthScore: 80, image: "https://images.unsplash.com/photo-1627811821845-45c5a1a51c69?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGFsaWF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 80, pricePerServing: 4, valueRating: 10, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt5-3", name: "Brown Rice", description: "Whole grain brown rice, good fiber source, more affordable than quinoa.", healthScore: 84, image: "https://images.unsplash.com/photo-1595514524374-a4410aabcb03?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YnJvd24lMjByaWNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 120, pricePerServing: 6, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] }
    ],
    "6": [
        { id: "alt6-1", name: "Millets (Ragi, Bajra, Jowar, Foxtail)", description: "Nutrient-dense Indian staple grains, comparable health benefits, often cheaper.", healthScore: 85, image: "https://images.unsplash.com/photo-1621588433159-42a6d700c6d2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWlsbGV0fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 160, pricePerServing: 8, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt6-2", name: "Dalia (Broken Wheat)", description: "Cracked wheat, good source of fiber, very affordable.", healthScore: 80, image: "https://images.unsplash.com/photo-1627811821845-45c5a1a51c69?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGFsaWF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 80, pricePerServing: 4, valueRating: 10, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt6-3", name: "Organic Quinoa", description: "Higher protein alternative, though generally more expensive.", healthScore: 90, image: "https://organicindia.com/cdn/shop/products/Quinoa_ing.jpg?v=1672736693", healthStatus: "healthy", price: 350, pricePerServing: 35, valueRating: 7, incomeSuitability: ["medium_low", "medium_high", "high"] }
    ],
    "7": [
        { id: "alt7-1", name: "Ragi Porridge Mix", description: "Finger millet porridge mix, high in calcium and fiber. Traditional healthy breakfast.", healthScore: 88, image: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/07/ragi-porridge-recipe-1.jpg", healthStatus: "healthy", price: 100, pricePerServing: 8, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt7-2", name: "Dalia (Broken Wheat)", description: "Can be made into a savory or sweet porridge, very filling and affordable.", healthScore: 80, image: "https://images.unsplash.com/photo-1627811821845-45c5a1a51c69?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGFsaWF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 80, pricePerServing: 3, valueRating: 10, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt7-3", name: "Millet Flakes (Mixed)", description: "Flaked millets offer similar texture to oats for porridge or upma.", healthScore: 82, image: "https://5.imimg.com/data5/ANDROID/Default/2021/8/GH/AZ/XN/86981218/product-jpeg-500x500.jpg", healthStatus: "healthy", price: 180, pricePerServing: 14, valueRating: 8, incomeSuitability: ["low", "medium_low", "medium_high", "high"] }
    ],
    "8": [
        { id: "alt8-1", name: "Ragi Flour (Finger Millet)", description: "Nutritious gluten-free flour, rich in calcium.", healthScore: 87, image: "https://images.unsplash.com/photo-1606853093344-b9a4a0797a1f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cmFnaSUyMGZsb3VyfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 90, pricePerServing: 9, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt8-2", name: "Jowar Flour (Sorghum)", description: "Another healthy gluten-free millet flour.", healthScore: 85, image: "https://rukminim1.flixcart.com/image/832/832/kqidx8w0/flour/g/x/k/jowar-flour-sorghum-flour-jowar-atta-gluten-free-low-gi-original-imag4gbzg9myhbhf.jpeg", healthStatus: "healthy", price: 100, pricePerServing: 10, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt8-3", name: "Besan (Gram Flour)", description: "Made from chickpeas, high protein, widely used in Indian cooking.", healthScore: 84, image: "https://images.unsplash.com/photo-1607672508145-8c3b193c8b1d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JhbSUyMGZsb3VyfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 120, pricePerServing: 12, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] }
    ],
    "9": [
        { id: "alt9-1", name: "Basil Seeds (Sabja)", description: "Similar gelling properties to chia, used in Indian drinks like Falooda. Cooling effect.", healthScore: 85, image: "https://images.unsplash.com/photo-1630476387399-9344504f6293?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmFzaWwlMjBzZWVkc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 150, pricePerServing: 11, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt9-2", name: "Flax Seeds (Alsi)", description: "Excellent source of omega-3s and fiber, cheaper than chia. Best ground before use.", healthScore: 88, image: "https://images.unsplash.com/photo-1591189863413-11998a4ccff9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZmxheCUyMHNlZWRzfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 200, pricePerServing: 12, valueRating: 8, incomeSuitability: ["medium_low", "medium_high", "high"] },
        { id: "alt9-3", name: "Pumpkin Seeds (Pepitas)", description: "Good source of magnesium, zinc, and healthy fats. Nutty flavor.", healthScore: 87, image: "https://images.unsplash.com/photo-1601057189390-65d9f3c69125?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cHVtcGtpbiUyMHNlZWRzfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 220, pricePerServing: 26, valueRating: 8, incomeSuitability: ["medium_low", "medium_high", "high"] },
    ],
    "10": [
        { id: "alt10-1", name: "Barley (Jau)", description: "Heart-healthy grain with good fiber content.", healthScore: 83, image: "https://images.unsplash.com/photo-1619426380393-999a3d1b2f53?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmFybGV5JTIwZ3JhaW5zfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 100, pricePerServing: 5, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt10-2", name: "Dalia (Broken Wheat)", description: "Affordable and versatile cracked wheat.", healthScore: 80, image: "https://images.unsplash.com/photo-1627811821845-45c5a1a51c69?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGFsaWF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 80, pricePerServing: 4, valueRating: 10, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt10-3", name: "Brown Rice", description: "Common whole grain alternative.", healthScore: 84, image: "https://images.unsplash.com/photo-1595514524374-a4410aabcb03?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YnJvd24lMjByaWNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 120, pricePerServing: 6, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] }
    ],
    "11": [
        { id: "alt11-1", name: "Toor Dal (Arhar Dal)", description: "Very common Indian lentil, staple food.", healthScore: 90, image: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/11/toor-dal-recipe-1.jpg", healthStatus: "healthy", price: 140, pricePerServing: 7, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt11-2", name: "Moong Dal (Split Green Gram)", description: "Easily digestible lentil, often used for khichdi.", healthScore: 91, image: "https://images.unsplash.com/photo-1605488693070-c2f366bbac6a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bW9vbmclMjBkYWx8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 150, pricePerServing: 8, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt11-3", name: "Chana Dal (Split Chickpeas)", description: "Nutty flavor, high in protein and fiber.", healthScore: 89, image: "https://images.unsplash.com/photo-1625944239187-16943907d17c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hhbmElMjBkYWx8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 130, pricePerServing: 7, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] }
    ],
    "12": [
        { id: "alt12-1", name: "Basil Seeds (Sabja)", description: "Similar gelling properties, cooling effect.", healthScore: 85, image: "https://images.unsplash.com/photo-1630476387399-9344504f6293?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmFzaWwlMjBzZWVkc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 150, pricePerServing: 11, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt12-2", name: "Sunflower Seeds", description: "Good source of Vitamin E and healthy fats.", healthScore: 86, image: "https://images.unsplash.com/photo-1606903364047-5f0b5b9a0f8c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3VuZmxvd2VyJTIwc2VlZHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 180, pricePerServing: 18, valueRating: 8, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt12-3", name: "Chia Seeds", description: "Nutrient-dense but often pricier alternative.", healthScore: 96, image: "https://images.unsplash.com/photo-1541713361671-96c6d5b5f4d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpYSUyMHNlZWRzfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 250, pricePerServing: 30, valueRating: 7, incomeSuitability: ["medium_low", "medium_high", "high"] }
    ],
    "13": [
        { id: "alt13-1", name: "Chickpea Pasta", description: "Gluten-free pasta made from chickpea flour, high protein.", healthScore: 90, image: "https://images.unsplash.com/photo-1630401813002-7a57a1335bc1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpY2twZWElMjBwYXN0YXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 280, pricePerServing: 45, valueRating: 7, incomeSuitability: ["medium_high", "high"] },
        { id: "alt13-2", name: "Zucchini Noodles ('Zoodles')", description: "Spiralized zucchini as a very low-carb pasta substitute.", healthScore: 95, image: "https://images.unsplash.com/photo-1560957486-a11f87259383?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8enVjY2hpbmklMjBub29kbGVzfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 60, pricePerServing: 60, valueRating: 8, incomeSuitability: ["medium_low", "medium_high", "high"] },
        { id: "alt13-3", name: "Millet Noodles", description: "Noodles made from various millet flours, healthier than refined flour.", healthScore: 80, image: "https://m.media-amazon.com/images/I/81M44-0+pWL.jpg", healthStatus: "healthy", price: 150, pricePerServing: 30, valueRating: 8, incomeSuitability: ["medium_low", "medium_high", "high"] }
    ],
    "14": [
        { id: "alt14-1", name: "Sprouted Moth Beans (Matki)", description: "Another commonly sprouted legume in India.", healthScore: 96, image: "https://img-global.cpcdn.com/recipes/34e6e287a17d910a/400x400cq70/photo.jpg", healthStatus: "healthy", price: 110, pricePerServing: 22, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt14-2", name: "Cooked Black Chana Salad", description: "Boiled black chickpeas mixed with salad veggies.", healthScore: 92, image: "https://images.unsplash.com/photo-1598511984240-25916f7a7ebc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmxhY2slMjBjaGFuYSUyMHNhbGFkfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 90, pricePerServing: 9, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt14-3", name: "Edamame (Steamed/Boiled)", description: "Young soybeans, good source of protein.", healthScore: 89, image: "https://images.unsplash.com/photo-1603201603433-06a3d5750f4a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZWRhbWFtZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 150, pricePerServing: 30, valueRating: 8, incomeSuitability: ["medium_low", "medium_high", "high"] }
    ],

    // Alternatives for Kurkure Masala Munch (ID: 15) - reusing alternatives from Potato Chips (ID: 4)
    "15": [
        { id: "alt4-1", name: "Baked Ragi Chips / Nachos", description: "Crunchy baked snacks made from Ragi (finger millet) flour. Healthier than fried potato chips.", healthScore: 70, image: "https://m.media-amazon.com/images/I/81a4ZtUeWSL.jpg", healthStatus: "moderate", price: 60, pricePerServing: 40, valueRating: 7, incomeSuitability: ["medium_low", "medium_high", "high"] },
        { id: "alt4-2", name: "Air-popped Popcorn (Lightly Salted)", description: "Whole grain, high-fiber snack when air-popped and lightly seasoned.", healthScore: 85, image: "https://images.unsplash.com/photo-1578849248041-36f7a84beb70?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cG9wY29ybnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 50, pricePerServing: 5, valueRating: 10, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt4-3", name: "Spiced Puffed Rice (Murmura Bhel - No Sev)", description: "Light puffed rice mixed with onions, tomatoes, and spices (skip fried sev for health).", healthScore: 75, image: "https://images.unsplash.com/photo-1601050690594-787f8d7c07f8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bXVybXVyYSUyMGJoZWx8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 70, pricePerServing: 15, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt4-4", name: "Roasted Chana (Chickpeas)", description: "Crunchy, savory, and protein-packed roasted chickpeas.", healthScore: 82, image: "https://images.unsplash.com/photo-1604467707600-5c7adbce6c63?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cm9hc3RlZCUyMGNoaWNrcGVhc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 80, pricePerServing: 16, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
    ],
    // Alternatives for Dairy Milk Chocolate (ID: 16) - reusing alternatives from Dark Chocolate Bar (ID: 1)
    "16": [
        { id: "alt1-1", name: "Banana + Peanut Butter", description: "Naturally sweet banana with protein-rich peanut butter. A satisfying, healthier treat.", healthScore: 85, image: "https://images.unsplash.com/photo-1615478503562-ec2d8aa0e24e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmFuYW5hJTIwcGVhbnV0JTIwYnV0dGVyfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 40, pricePerServing: 40, valueRating: 9, incomeSuitability: ["low", "medium_low", "medium_high", "high"] },
        { id: "alt1-2", name: "Greek Yogurt + Cocoa + Berries", description: "High-protein yogurt with unsweetened cocoa and antioxidant-rich berries.", healthScore: 90, image: "https://images.unsplash.com/photo-1587477615013-357d68b6951a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JlZWslMjB5b2d1cnQlMjBjaG9jb2xhdGUlMjBiZXJyaWVzfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60", healthStatus: "healthy", price: 80, pricePerServing: 80, valueRating: 8, incomeSuitability: ["medium_low", "medium_high", "high"] },
        { id: "alt1-3", name: "Amul 90% Dark Chocolate", description: "Very dark chocolate with lower sugar content. Intense cocoa flavour.", healthScore: 75, image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRYzOJvAhNUgdflE1jxmPPQFxi6Ja72lxvPDY1qRudbag66Rp8IJQrZSZ0I9R_M4Vczs6xEM1uEY4G31Jbb3ZIhl5nlD9unjbCs6KZdR_3kfc6MaYqLzHNQUA", healthStatus: "moderate", price: 130, pricePerServing: 43, valueRating: 8, incomeSuitability: ["medium_low", "medium_high", "high"] }
    ]
};

// END OF UPDATED data.js